<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Core gateways (slug => definition).
    | Plugins may register additional gateways via GatewayRegistry::register().
    |--------------------------------------------------------------------------
    */
    'gateways' => [
        'cajupay' => [
            'slug' => 'cajupay',
            'name' => 'CajuPay',
            'image' => 'images/gateways/cajupay.png',
            'methods' => ['pix', 'card', 'apple_pay', 'google_pay', 'pix_parcelado', 'pix_auto'],
            'scope' => 'international',
            'country' => 'br',
            'country_name' => 'Brasil / Global',
            'country_flag' => 'brasil.png',
            'countries' => [
                ['flag' => 'brasil.png', 'name' => 'Brasil'],
                ['flag' => 'global.png', 'name' => 'Global'],
            ],
            'signup_url' => 'https://cajupay.com.br',
            'driver' => \App\Gateways\CajuPay\CajuPayDriver::class,
            'credential_keys' => [
                [
                    'key' => 'public_key',
                    'label' => 'Chave pública',
                    'type' => 'text',
                    'hint' => 'Produção: gpk_… · Sandbox: gpk_test_… (painel CajuPay → API / Chaves). Ao salvar, o Getfy registra o webhook automaticamente.',
                ],
                [
                    'key' => 'secret_key',
                    'label' => 'Chave secreta',
                    'type' => 'password',
                    'hint' => 'Produção: gsk_… · Sandbox: gsk_test_… Necessária junto com a chave pública.',
                ],
                [
                    'key' => 'sandbox',
                    'label' => 'Usar ambiente sandbox (chaves de teste)',
                    'type' => 'boolean',
                    'hint' => 'Ative com chaves gpk_test_ / gsk_test_. O SDK mostra banner de teste e cartão digitado funciona em HTTP. Chaves live (gpk_/gsk_) não podem forçar sandbox.',
                ],
                [
                    'key' => 'webhook_signing_secret',
                    'label' => 'Token do webhook (signing secret)',
                    'type' => 'password',
                    'optional' => true,
                    'advanced' => true,
                    'hint' => 'Preenchido automaticamente ao salvar as chaves. Só edite se rotacionou manualmente no painel CajuPay. Deixe em branco ao salvar para manter o token já gravado.',
                ],
            ],
        ],
        'efi' => [
            'slug' => 'efi',
            'name' => 'Efí',
            'image' => 'images/gateways/efi.png',
            'methods' => ['pix', 'card', 'boleto', 'pix_auto'],
            'scope' => 'national',
            'country' => 'br',
            'country_name' => 'Brasil',
            'country_flag' => 'brasil.png',
            'signup_url' => 'https://sejaefi.com.br',
            'driver' => \App\Gateways\Efi\EfiDriver::class,
            'certificate_key' => 'certificate',
            'credential_keys' => [
                ['key' => 'client_id', 'label' => 'Client ID', 'type' => 'text'],
                ['key' => 'client_secret', 'label' => 'Client Secret', 'type' => 'password'],
                ['key' => 'pix_key', 'label' => 'Chave PIX (E‑mail, CPF, CNPJ ou aleatória)', 'type' => 'text'],
                ['key' => 'payee_code', 'label' => 'Identificador de conta (payee_code) — para cartão', 'type' => 'text'],
                ['key' => 'sandbox', 'label' => 'Usar ambiente de homologação (sandbox)', 'type' => 'boolean'],
                ['key' => 'certificate', 'label' => 'Certificado P12', 'type' => 'file'],
            ],
        ],
        'stripe' => [
            'slug' => 'stripe',
            'name' => 'Stripe',
            'image' => 'images/gateways/stripe.png',
            'methods' => ['card'],
            'scope' => 'international',
            'country_flag' => 'global.png',
            'country_name' => 'Global',
            'signup_url' => 'https://dashboard.stripe.com/register',
            'driver' => \App\Gateways\Stripe\StripeDriver::class,
            'credential_keys' => [
                ['key' => 'secret_key', 'label' => 'Secret Key', 'type' => 'password'],
                ['key' => 'publishable_key', 'label' => 'Publishable Key', 'type' => 'text'],
                ['key' => 'webhook_secret', 'label' => 'Webhook Secret (whsec_...)', 'type' => 'password'],
                ['key' => 'sandbox', 'label' => 'Usar ambiente de teste', 'type' => 'boolean'],
                ['key' => 'link_enabled', 'label' => 'Habilitar Stripe Link no checkout', 'type' => 'boolean'],
            ],
        ],
        'mercadopago' => [
            'slug' => 'mercadopago',
            'name' => 'Mercado Pago',
            'image' => 'images/gateways/mercado-pago.webp',
            'methods' => ['pix', 'card', 'boleto'],
            'scope' => 'international',
            'country' => 'br',
            'country_name' => 'Brasil, Argentina, Chile, Colômbia, México, Peru, Uruguai',
            'country_flag' => 'brasil.png',
            'countries' => [
                ['flag' => 'brasil.png', 'name' => 'Brasil'],
                ['flag' => 'argentina.png', 'name' => 'Argentina'],
                ['flag' => 'chile.png', 'name' => 'Chile'],
                ['flag' => 'colombia.png', 'name' => 'Colômbia'],
                ['flag' => 'mexico.png', 'name' => 'México'],
                ['flag' => 'peru.png', 'name' => 'Peru'],
                ['flag' => 'uruguay.png', 'name' => 'Uruguai'],
            ],
            'signup_url' => 'https://www.mercadopago.com.br/developers',
            'driver' => \App\Gateways\MercadoPago\MercadoPagoDriver::class,
            'credential_keys' => [
                ['key' => 'public_key', 'label' => 'Public Key', 'type' => 'text'],
                ['key' => 'access_token', 'label' => 'Access Token', 'type' => 'password'],
                ['key' => 'sandbox', 'label' => 'Usar sandbox (credenciais de teste)', 'type' => 'boolean'],
            ],
        ],
        'pushinpay' => [
            'slug' => 'pushinpay',
            'name' => 'Pushin Pay',
            'image' => 'images/gateways/pushinpay.png',
            'methods' => ['pix', 'pix_auto'],
            'scope' => 'national',
            'country' => 'br',
            'country_name' => 'Brasil',
            'country_flag' => 'brasil.png',
            'signup_url' => 'https://app.pushinpay.com.br/register',
            'driver' => \App\Gateways\PushinPay\PushinPayDriver::class,
            'credential_keys' => [
                ['key' => 'api_token', 'label' => 'API Token', 'type' => 'password'],
                ['key' => 'sandbox', 'label' => 'Usar ambiente de homologação (sandbox)', 'type' => 'boolean'],
            ],
        ],
        'asaas' => [
            'slug' => 'asaas',
            'name' => 'Asaas',
            'image' => 'images/gateways/asaas.png',
            'methods' => ['pix', 'card', 'boleto'],
            'scope' => 'national',
            'country' => 'br',
            'country_name' => 'Brasil',
            'country_flag' => 'brasil.png',
            'signup_url' => 'https://www.asaas.com',
            'driver' => \App\Gateways\Asaas\AsaasDriver::class,
            'credential_keys' => [
                ['key' => 'api_key', 'label' => 'API Key', 'type' => 'password'],
                ['key' => 'sandbox', 'label' => 'Usar ambiente de homologação (sandbox)', 'type' => 'boolean'],
            ],
        ],
        'pagarme' => [
            'slug' => 'pagarme',
            'name' => 'Pagar.me',
            'image' => 'images/gateways/pagarme.png',
            'methods' => ['pix', 'card', 'boleto'],
            'scope' => 'national',
            'country' => 'br',
            'country_name' => 'Brasil',
            'country_flag' => 'brasil.png',
            'signup_url' => 'https://pagar.me',
            'driver' => \App\Gateways\Pagarme\PagarmeDriver::class,
            'checkout_payload_keys' => ['public_key'],
            'credential_keys' => [
                ['key' => 'secret_key', 'label' => 'Secret Key', 'type' => 'password'],
                ['key' => 'public_key', 'label' => 'Public Key', 'type' => 'text'],
                ['key' => 'sandbox', 'label' => 'Sandbox', 'type' => 'boolean'],
            ],
        ],
        'paypal' => [
            'slug' => 'paypal',
            'name' => 'PayPal',
            'image' => 'images/gateways/paypal.png',
            'methods' => ['paypal'],
            'scope' => 'international',
            'country_flag' => 'global.png',
            'country_name' => 'Global',
            'signup_url' => 'https://developer.paypal.com/dashboard/',
            'driver' => \App\Gateways\PayPal\PayPalDriver::class,
            'checkout_payload_keys' => ['client_id'],
            'credential_keys' => [
                [
                    'key' => 'client_id',
                    'label' => 'Client ID',
                    'type' => 'text',
                    'hint' => 'Client ID do app REST no PayPal Developer Dashboard (sandbox ou live).',
                ],
                [
                    'key' => 'client_secret',
                    'label' => 'Client Secret',
                    'type' => 'password',
                    'hint' => 'Client Secret do mesmo app. Nunca é exposto no checkout.',
                ],
                [
                    'key' => 'webhook_id',
                    'label' => 'Webhook ID',
                    'type' => 'text',
                    'hint' => 'No bloco Webhook acima, copie a URL e cadastre no PayPal Developer Dashboard. Depois cole aqui o Webhook ID gerado. Eventos: PAYMENT.CAPTURE.COMPLETED, PAYMENT.CAPTURE.DENIED, PAYMENT.CAPTURE.REFUNDED.',
                ],
                [
                    'key' => 'sandbox',
                    'label' => 'Usar ambiente Sandbox',
                    'type' => 'boolean',
                    'hint' => 'Ative com credenciais sandbox; desative em produção com Client ID/Secret live.',
                ],
                [
                    'key' => 'checkout_mode',
                    'label' => 'Modo no checkout',
                    'type' => 'select',
                    'options' => [
                        ['value' => 'auto', 'label' => 'Automático (campos na página → botão cartão → wallet)'],
                        ['value' => 'expanded', 'label' => 'Campos de cartão na página (Expanded)'],
                        ['value' => 'buttons', 'label' => 'Botão cartão PayPal (abre os inputs)'],
                        ['value' => 'wallet', 'label' => 'Conta PayPal (popup)'],
                    ],
                    'hint' => 'Prefira Automático ou Expanded para inputs na página. Contas BR muitas vezes não têm Expanded; aí aparece o botão de cartão da PayPal. Use “Conta PayPal” só se quiser o popup da carteira.',
                ],
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Default redundancy order per method (when tenant has not configured).
    |--------------------------------------------------------------------------
    */
    'default_order' => [
        'pix' => ['cajupay', 'efi', 'mercadopago', 'pagarme', 'pushinpay', 'asaas'],
        'card' => ['cajupay', 'efi', 'stripe', 'mercadopago', 'pagarme', 'asaas'],
        'boleto' => ['efi', 'mercadopago', 'pagarme', 'asaas'],
        'pix_auto' => ['cajupay', 'efi', 'pushinpay'],
        'apple_pay' => ['cajupay'],
        'google_pay' => ['cajupay'],
        'paypal' => ['paypal'],
        'pix_parcelado' => ['cajupay'],
        'crypto' => [],
    ],
];
